# Generated by Django 4.0.6 on 2022-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapi', '0002_alter_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_desc',
            field=models.CharField(max_length=300, verbose_name='postDesc'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='postImg'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateField(auto_now_add=True, verbose_name='postDate'),
        ),
    ]
