# Generated by Django 4.0.6 on 2022-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapi', '0003_alter_post_post_desc_alter_post_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_desc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
